default_agent: longrunning_langraph_agent
agents:
  longrunning_langraph_agent:
    name: longrunning_langraph_agent
    language: python
    node_version: '20'
    entrypoint: /Users/sbattoo/Src/MockLongRunningLangraphAgent/agentcore_agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: /Users/sbattoo/Src/MockLongRunningLangraphAgent
    aws:
      execution_role: arn:aws:iam::175918693907:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-b4f2bab3e5
      execution_role_auto_create: false
      account: '175918693907'
      region: us-west-2
      ecr_repository: 175918693907.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-longrunning_langraph_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: longrunning_langraph_agent-7Z3Fu233jt
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:175918693907:runtime/longrunning_langraph_agent-7Z3Fu233jt
      agent_session_id: feaf6d5f-5eac-41e0-9df6-8b59bcf25fe6
    codebuild:
      project_name: bedrock-agentcore-longrunning_langraph_agent-builder
      execution_role: arn:aws:iam::175918693907:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-b4f2bab3e5
      source_bucket: bedrock-agentcore-codebuild-sources-175918693907-us-west-2
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
